let menu=[],cart=[];
const categories=["All","Starters","Veg","Non-Veg","Biryanis","Breads","Drinks"];

async function load(){menu=await fetch("/api/menu").then(r=>r.json());renderFilters();render(menu)}
function renderFilters(){document.getElementById("filters").innerHTML=categories.map((c,i)=>`<button class="filter ${i===0?"active":""}" onclick="filter('${c}',this)">${c}</button>`).join("")}
function filter(c,el){document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));el.classList.add("active");render(c==="All"?menu:menu.filter(x=>c==="Veg"?x.type==="veg":c==="Non-Veg"?x.type==="nonveg":c==="Drinks"?x.type==="drink":x.category===c))}
function render(items){document.getElementById("grid").innerHTML=items.map(x=>`<article class="card"><img src="${x.image}" alt="${esc(x.name)}" loading="lazy"><div class="body"><span class="badge ${x.type}">${x.type==="veg"?"🟢 VEG":x.type==="nonveg"?"🔴 NON-VEG":"🥤 DRINK"}</span>${x.spice!=="None"?`<span class="badge">${x.spice==="Mild"?"🌶️ Mild":x.spice==="Medium"?"🌶️🌶️ Medium":"🌶️🌶️🌶️ Spicy"}</span>`:""}<h3>${esc(x.name)}</h3><p>${esc(x.description)}</p><div class="prices"><span>Half ₹${x.half||"—"}</span><span>Full ₹${x.full||"—"}</span></div><button class="add" ${!x.full?"disabled":""} onclick="add(${x.id})">${x.full?"ADD TO CART":"SET PRICE FIRST"}</button></div></article>`).join("")}
function add(id){let x=menu.find(a=>a.id===id),found=cart.find(a=>a.id===id&&a.size==="full");if(found)found.quantity++;else cart.push({id:x.id,name:x.name,size:"full",price:x.full,quantity:1});update();openCart()}
function update(){document.getElementById("count").textContent=cart.reduce((s,x)=>s+x.quantity,0);document.getElementById("total").textContent=cart.reduce((s,x)=>s+x.price*x.quantity,0);document.getElementById("cartItems").innerHTML=cart.length?cart.map((x,i)=>`<div class="line"><div><b>${esc(x.name)}</b><br>Full × ${x.quantity}<br><button onclick="qty(${i},-1)">−</button> <button onclick="qty(${i},1)">+</button></div><b>₹${x.price*x.quantity}</b></div>`).join(""):"<p>Your cart is empty.</p>"}
function qty(i,n){cart[i].quantity+=n;if(cart[i].quantity<1)cart.splice(i,1);update()}
function openCart(){document.getElementById("cartModal").classList.remove("hidden");update()}
function closeCart(){document.getElementById("cartModal").classList.add("hidden")}
function checkout(){if(!cart.length)return alert("Your cart is empty.");closeCart();document.getElementById("checkoutModal").classList.remove("hidden")}
function closeCheckout(){document.getElementById("checkoutModal").classList.add("hidden")}
document.getElementById("form").addEventListener("submit",async e=>{e.preventDefault();const body={customer:{name:document.getElementById("name").value,phone:document.getElementById("phone").value,email:document.getElementById("email").value,address:document.getElementById("address").value},items:cart,paymentMethod:document.querySelector('input[name="payment"]:checked').value};const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();document.getElementById("result").textContent=r.ok?`Order ${d.orderNumber} received. Payment status: ${d.paymentStatus}.`:(d.error||"Order failed.");if(r.ok){cart=[];update();e.target.reset()}})
function toggleAI(){document.getElementById("ai").classList.toggle("hidden")}
async function askAI(){const input=document.getElementById("question"),q=input.value.trim();if(!q)return;const chat=document.getElementById("chat");chat.innerHTML+=`<div class="user">${esc(q)}</div>`;input.value="";const r=await fetch("/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:q})});const d=await r.json();chat.innerHTML+=`<div class="bot">${esc(d.reply)}</div>`;chat.scrollTop=chat.scrollHeight}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
document.getElementById("year").textContent=new Date().getFullYear();load();
